# Generated by Django 2.0.10 on 2019-01-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('home_size', models.PositiveIntegerField(blank=True, null=True)),
                ('home_type', models.CharField(blank=True, max_length=32, null=True)),
                ('last_sold_date', models.DateField(blank=True, null=True)),
                ('last_sold_price', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=1024, null=True)),
                ('price', models.CharField(blank=True, max_length=32, null=True)),
                ('property_size', models.PositiveIntegerField(blank=True, null=True)),
                ('rent_price', models.PositiveIntegerField(blank=True, null=True)),
                ('rentzestimate_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('rentzestimate_last_updated', models.DateField(blank=True, null=True)),
                ('tax_value', models.PositiveIntegerField(blank=True, null=True)),
                ('tax_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('zestimate_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('zestimate_last_updated', models.DateField(blank=True, null=True)),
                ('zillow_id', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=8, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
